server:
  port: 7070

eureka:
  instance:
    hostname: inst1
  client:
    serviceUrl:
      defaultZone: http://inst1:7000/eureka/


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inst01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
#  data:
#    mongodb:
#      uri: mongodb://10.37.147.250:27017/bytetcc
#  cloud:
#    zookeeper:
#      connectString: 127.0.0.1:2181
